### PR TITLE
[WIP] - Working on dedicated cluster networking option

### PR DESCRIPTION
**Pull request by jshcmpbll**

### CODE REVIEW

**Comment by linouk23** [comment]
👋 @jshcmpbll, thanks for creating a PR!

We actually implemented networking resources already to support
* _Dedicated_ Kafka cluster that is accessible via PrivateLink connections
* _Dedicated_ Kafka cluster that is accessible via VPC Peering connections

but we're testing these out at the moment before making these available.

**Comment by jshcmpbll** [comment]
Love to hear it :D

**Comment by dstendardi** [comment]
Looking forward also to see this issue solved !

**Comment by linouk23** [comment]
@dstendardi that's great to hear! It might be a good idea to subscribe to https://github.com/confluentinc/terraform-provider-confluentcloud/issues/45 then.

**Pull request closed without merging**
