### PR TITLE
enable confluent cloud platform roles for role bindings in ccloud …

### PR DESCRIPTION
**Pull request by ngapaillard**
Hi !
In our company we start to use RBAC with cloud platform predefined roles in our confluent cloud subscription. We'd like very much to provision it through terraform that is our reference provisionning tool.
My modification was just to add new accepted roles in role validation. It seems to me that is enough because today the resource definition is done through crn pattern that seems very generic.

Please don't hesitate if you have any question or remarks.

### CODE REVIEW

**Comment by linouk23** [comment]
Thanks for creating a PR @ngapaillard!

That sounds like a good idea, let's see whether we'll be able to include it in our next release which is about to happen.

FYI we'll be also introducing new `rbac_crn` attribute for a `confluentcloud_kafka_cluster` which should simplify the process of using `crn_pattern` attribute when creating `confluentcloud_role_binding` resource.

**Comment by ngapaillard** [comment]
Thanks for your reply, it's a very good news if it can be in the next release. And thanks for information about future usage of the provider. We will take care of that ;)

**Comment by ngapaillard** [comment]
Hi,
Just for my information, do you have a due date for the next release ? 
Thanks,

**Comment by linouk23** [comment]
Most likely it'll happen either today or on Monday, I'll keep you updated!

**Comment by linouk23** [comment]
@ngapaillard check out `0.4.0` release and specifically this doc about `confluentcloud_role_binding` resource.

**Comment by ngapaillard** [comment]
Oh thanks, so fast ! We will implement it as soon, thanks again !

**Comment by linouk23** [comment]
You're welcome! Please let us now if you run into any issues / post general feedback under our [issues](https://github.com/confluentinc/terraform-provider-confluentcloud/issues) page.

**Pull request closed without merging**
